services:
  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: blog_backend
    environment:
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - JWT_ALGORITHM=HS256
      - JWT_EXPIRATION=3600
      - DEBUG=true
      - ENVIRONMENT=development
      - API_PREFIX=/api
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - blog_network
    restart: unless-stopped

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: blog_frontend
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_ENVIRONMENT=development
    ports:
      - "3000:80"
    networks:
      - blog_network
    restart: unless-stopped

volumes:

networks:
  blog_network:
    driver: bridge 